/**
 * This code was generated by @basketry/typescript-dtos@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://basketry.io
 * About @basketry/typescript-dtos: https://basketry.io/docs/components/@basketry/typescript-dtos
 */

import type * as types from '../types';
import type * as dtos from './types';

function compact<T extends object>(obj: T): T {
  return Object.keys(obj).reduce((acc, key) => {
    const value = obj[key as keyof T];
    if (value !== undefined) {
      acc[key as keyof T] = value;
    }
    return acc;
  }, {} as T);
}

export function mapFromCreateWidgetStringDto(
  dto: dtos.CreateWidgetStringDto,
): types.CreateWidgetString {
  return compact({
    name: dto.name,
  });
}

export function mapFromExhaustiveParamsStringDto(
  dto: dtos.ExhaustiveParamsStringDto,
): types.ExhaustiveParamsString {
  return compact({
    foo: dto.foo,
    bar: dto.bar,
  });
}

export function mapToGetGizmosResponseDto(
  obj: types.GetGizmosResponse,
): dtos.GetGizmosResponseDto {
  return compact({
    data: obj.data?.map(mapToGizmoDto),
  });
}

export function mapToGizmoDto(obj: types.Gizmo): dtos.GizmoDto {
  return compact({
    id: obj.id,
    name: obj.name,
    size: obj.size,
  });
}

export function mapToWidgetDto(obj: types.Widget): dtos.WidgetDto {
  return compact({
    id: obj.id,
    name: obj.name,
    fiz: obj.fiz,
    buzz: obj.buzz,
    fizbuzz: obj.fizbuzz,
    foo:
      typeof obj.foo === 'undefined' ? undefined : mapToWidgetFooDto(obj.foo),
    size: obj.size,
  });
}

export function mapToWidgetFooDto(obj: types.WidgetFoo): dtos.WidgetFooDto {
  return compact({
    fiz: obj.fiz,
    buzz: obj.buzz,
  });
}
