/**
 * This code was generated by @basketry/typescript-dtos@{{version}}
 *
 * Changes to this file may cause incorrect behavior and will be lost if
 * the code is regenerated.
 *
 * To make changes to the contents of this file:
 * 1. Edit source/path.ext
 * 2. Run the Basketry CLI
 *
 * About Basketry: https://basketry.io
 * About @basketry/typescript-dtos: https://basketry.io/docs/components/@basketry/typescript-dtos
 */

import type * as types from '../types';

/** The over-the-wire representation of the {@link types.CreateWidgetString|CreateWidgetString} type. */
export type CreateWidgetStringDto = {
  name?: string;
};

/** The over-the-wire representation of the {@link types.ExhaustiveParamsString|ExhaustiveParamsString} type. */
export type ExhaustiveParamsStringDto = {
  bar?: string;
  foo?: string;
};

/** The over-the-wire representation of the {@link types.GetGizmosResponse|GetGizmosResponse} type. */
export type GetGizmosResponseDto = {
  data?: GizmoDto[];
};

/** The over-the-wire representation of the {@link types.Gizmo|Gizmo} type. */
export type GizmoDto = {
  id?: string;
  name?: string;
  size?: types.ProductSize;
};

/** The over-the-wire representation of the {@link types.Widget|Widget} type. */
export type WidgetDto = {
  buzz?: number;
  fiz?: number;
  fizbuzz?: number;
  foo?: WidgetFooDto;
  id?: string;
  name?: string;
  size?: types.ProductSize;
};

/** The over-the-wire representation of the {@link types.WidgetFoo|WidgetFoo} type. */
export type WidgetFooDto = {
  buzz?: number;
  fiz?: 123456;
};
